include: ./base.yaml

observation:
  pipeline:
  - name: limited_action_space
  - name: action_repeat
    count: 4
  - name: resize
    width: 120
    height: 112
  - name: grayscale
  - name: frame_buffer
    count: 2