# using same hyperparameters as the atari paper
algorithm: atari_dqn

env:
  game: "SuperMarioBros-Nes-v0"
  render_mode: None
model:
  type: atari_cnn
# 50 million total frames, 12.5 million action steps, 3 mil gradient steps
# all values here are converted to action steps
training:
  num_envs: 16
  total_steps: 12500000
  lr: 0.00025
  gamma: 0.99

  batch_size: 32
  #shrunk due to memory limitations
  buffer_size: 500000

  epsilon_start: 1.0
  epsilon_min: 0.1
  #1m frames
  epsilon_steps: 250000

  grad_momentum: 0.95
  squared_momentum: 0.95
  ms_grad: 0.01
# 10k param updates, 40k action steps
  update_target_steps: 40000
  grad_update_freq: 4
  action_repeat: 4
  save_every: 250000

  replay_start_size: 50000

observation:
  pipeline:
  - name: resize
    width: 84
    height: 84
  - name: grayscale
  - name: frame_buffer
    count: 4
  - name: action_repeat
    count: 4

reward:
  pipeline:
  - name: reset
  - name: ram_death_penalty
    penalty: -1
  - name: survival
    value: -0.05
  - name: earn_score
    weight: 0.02
    #flat bonus
  - name: screen_scroll
    weight: 0.1
    #based on speed
  - name: screen_scroll_amount
    weight: 0.05