# using same hyperparameters as the atari paper
algorithm: ramario

env:
  game: "SuperMarioBros-Nes-v0"
  render_mode: none

model:
  type: atari_cnn

training:
  num_envs: 16

  batch_size: 32
  buffer_size: 10000

  epsilon_start: 1.0
  epsilon_min: 0.1
  epsilon_steps: 8

  total_steps: 100
  episodes_per_task: 10
  num_grad_steps: 10
  lr: 0.001
  inner_lr: 0.001
  gamma: 0.99

  save_every: 10


observation:
  pipeline:
  - name: limited_action_space
  - name: action_repeat
    count: 4
  - name: resize
    width: 84
    height: 84
  - name: grayscale
  - name: frame_buffer
    count: 4


reward:
  pipeline:
  - name: reset
  - name: ram_death_penalty
    penalty: -1
  - name: earn_score
    weight: 0.02
  - name: screen_scroll
    weight: 0.1
  - name: screen_scroll_amount
    weight: 0.05