
algorithm: atari_dqn
env:
  game: "SuperMarioBros-Nes-v0"
  render_mode: none
model:
  type: atari_cnn

training:
  num_envs: 16
  total_steps: 2000000
  lr: 0.0005
  gamma: 0.99

  batch_size: 64
  buffer_size: 250000

  epsilon_start: 1.0
  epsilon_min: 0.1
  #1m frames
  epsilon_steps: 250000

  grad_momentum: 0.95
  squared_momentum: 0.95
  ms_grad: 0.01
# 10k param updates, 40k action steps
  update_target_steps: 10000
  grad_update_freq: 4
  action_repeat: 4
  save_every: 500000

  replay_start_size: 50000

observation:
  pipeline:
  - name: limited_action_space
  - name: action_repeat
    count: 4
  - name: resize
    width: 120
    height: 112
  - name: grayscale
  - name: frame_buffer
    count: 4